// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EojEMTJebCx6PYS8pd-OLSx_a4Q6e4w',
    appId: '1:769555555541:web:381c3d48f82a48d9c56e5c',
    messagingSenderId: '769555555541',
    projectId: 'trongtrepro-309aa',
    authDomain: 'trongtrepro-309aa.firebaseapp.com',
    storageBucket: 'trongtrepro-309aa.appspot.com',
    measurementId: 'G-ZZTBRSMHX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8J_Jn26w36UrqPgHgBT3q3l2WptO_XY',
    appId: '1:769555555541:android:d30c969aef3b3ddac56e5c',
    messagingSenderId: '769555555541',
    projectId: 'trongtrepro-309aa',
    storageBucket: 'trongtrepro-309aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD061CXPq8R1T2CezDXUGoHy_Inv11Gyo',
    appId: '1:769555555541:ios:8185f5e760dc9d28c56e5c',
    messagingSenderId: '769555555541',
    projectId: 'trongtrepro-309aa',
    storageBucket: 'trongtrepro-309aa.appspot.com',
    iosBundleId: 'com.example.trongTre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD061CXPq8R1T2CezDXUGoHy_Inv11Gyo',
    appId: '1:769555555541:ios:27c733f788d8f5bdc56e5c',
    messagingSenderId: '769555555541',
    projectId: 'trongtrepro-309aa',
    storageBucket: 'trongtrepro-309aa.appspot.com',
    iosBundleId: 'com.example.trongTre.RunnerTests',
  );
}
